### ISSUE TITLE
Take control display only

### ISSUE THREAD

**Issue by GeorgesDick** [wh1te909/rmmagent#3]
Since a couple of days, when I try to "take control" over a PC, I can see his screen, send commands using the menu on the bottom-right ("Alt + Ctrl + Suppr", "Win", etc.), send text ("Type" button), but the mouse and my keayboard are not "captured".
I checked every settings I could find, but none changed this strange behavior.

**Comment by wh1te909** [comment]
hi, this is the wrong repo. take control is handled by MeshCentral (separate product, we just integrate with them). You need to open an issue there https://github.com/Ylianst/MeshCentral
