### ISSUE TITLE
Repository source code is out of sync

### ISSUE THREAD

**Issue by sarog** [wh1te909/rmmagent#4]
Hi, since version 1.5.1, this repository has yet to receive the source code of later agent releases. While I'm aware the MIT License is quite permissive in this regard, a few sysadmins (such as myself) prefer to review code before deployment when given the opportunity.

Are there any plans to release the revised agent sources, or is this repo simply for closed-source binary releases from here on out?

Thank you for your time.

**Comment by montythibault-v2** [comment]
Agreed, deployment of a closed-source agent executable is not viable. Assuming it's just a temporary hiccup.

**Comment by rgmz** [comment]
See: https://www.reddit.com/r/sysadmin/comments/rq5g9h/a_few_concerns_with_tacticalrmm_am_i_being

**Comment by sarog** [comment]
😑
